# Plot colors
green:  "#B9D97C"  # tulight (approx. tugreen!20!white)
blue:   "#6CA0DC"  # soft, fresh blue
red:    "#D6655A"  # warm, balanced red
orange: "#F6A960"  # natural, light orange
pink:   "#DE7FAF"   # friendly, soft pink
black:  "#000000"  # standard black