name: trackcalib2
channels:
  - conda-forge
  - defaults
dependencies:
  - awkward>=1.8.0
  - colorama=0.4.4
  - dask-awkward>=2023.10.0
  - decorator>=5.0.9
  - iminuit>=2.4.0
  - ipython>=7.24.1
  - jax>=0.2.16
  - jaxlib>=0.1.68
  - matplotlib>=3.5.1
  - matplotlib-inline>=0.1.2
  - mergedeep>=1.3.4
  - mplhep>=0.3.23
  - numba>=0.53.1
  - numexpr>=2.9.0
  - numpy>=1.20.3
  - pandas>=1.3.0
  - prettytable>=3.2.0
  - scipy>=1.8.0
  - seaborn>=0.11.2
  - setuptools-scm>=6.0.1
  - tomli>=2.0.1
  - uncertainties>=3.1.5
  - uproot>=5.0.9
  - uproot3>=3.14.4
  - uproot3-methods>=0.10.1
  - xrootd>=5.6.0